#!/bin/bash

SCRIPT_DIR=$(dirname $0)
export PYTHONPATH=$SCRIPT_DIR/../../

PYTEST=$SCRIPT_DIR/test.py
SERVERS="alpha beta gamma"

for srv in $SERVERS
do
    rm -f /run/$srv.pid &> /dev/null
done
rm -rf *.log* &> /dev/null
killall -9 twistd &> /dev/null
python $PYTEST $@
